### ISSUE TITLE
details about modifing marked lib

### ISSUE THREAD

**Issue by layerssss** [qiao/coffee-box#3]
what is the reason?

**Comment by qiao** [comment]
The original `marked` library tends to wrap the colorized code snippets into a `<p>` element, which is not desired.

Before:

``````
```python
print 1
```
``````

After pygments:

``` html
<div class="highlight">
  <pre>
    <span class="k">print</span> <span class="mi">1</span>
  </pre>
</div>
```

After marked:

``` html
<p>
  <div class="highlight">
    <pre>
      <span class="k">print</span> <span class="mi">1</span>
    </pre>
  </div>
</p>
```

Notice that the `<p>` wrapper is superfluous.
So I modified `marked` to suppress this behavior.
